version: "3.8"
services:
  gitlab-deployer:
    image: danger89/gitlab-deployer:latest
    container_name: gitlab-deployer
    networks:
      - gitlab_deployer_external_network
    volumes:
      # Mount the local .env and dest folder (create a local dest folder first or update to another destination folder)
      # Be sure the destination host folder as the correct rights under Linux (UID: 1000 and GID 1000)
      - ./.env:/app/.env:ro
      # If the artifact was stored in a sub-folder (eg. dist), you need to use for example: ./dest:/app/dest/dist
      - ./dest:/app/dest
    ports:
      # If your service is running behind Nginx, you can make the service only lisen on localhost
      # using: "127.0.0.1:3042:3042"
      - "3042:3042"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: "1"
          memory: 150M

networks:
  gitlab_deployer_external_network:
